name: symai

channels:
  - default
  - conda-forge
  - pytorch
  - nvidia

dependencies:
  - python
  - setuptools
  - toml
  - natsort
  - numpy
  - tqdm
  - python-box
  - scikit-learn
  - pytorch
  - pytorch-cuda
  - torchvision
  - torchaudio
  - pyyaml
  - transformers
  - openai
  - pypdf2
  - ipython
  - beautifulsoup4
  - selenium
  - rpyc
  - accelerate
  - sentencepiece
  - webdriver-manager
  - pandas
  - tika
  - pip

  - pip:
    - sympy
    - symbolicai[all]
